### ISSUE TITLE
Make each card link to github

### ISSUE THREAD

**Issue by dillionverma** [dillionverma/github-issues-explorer#1]
Add functionality so that clicking on a card links to that specific issue on github

![image](https://user-images.githubusercontent.com/16860528/46847280-7de70e00-cdb1-11e8-9585-fc7d97a06619.png)

To do this, you can either use a classic html `<a />` tag or if you are more advanced, pass an `onClick` prop to the card and handle the click event by redircting to the specific url

**Comment by ktan114** [comment]
I can take a look at this.

**Comment by dillionverma** [comment]
Sounds good, let me know if you have any questions @ktan114

**Comment by alexmeji** [comment]
I have the solution for this @dillionverma
