### ISSUE TITLE
Add a css loading spinner!

### ISSUE THREAD

**Issue by dillionverma** [dillionverma/github-issues-explorer#14]
This is a very beginner friendly issue!

In the file [Issues.js](https://github.com/dillionverma/github-issues-explorer/blob/master/src/features/Issues/Issues.js) you will notice that an `isLoading` prop is passed to the Component. 

Your task will be to use that prop and display a loading spinner while `isLoading` is true. Look into any spinner of your choice and be creative!

*Hint: [This](http://kyleamathews.github.io/react-spinkit/) might be a good library for spinners if you are stuck.*

**Comment by johnrackles** [comment]
I'll do it :)

**Comment by dillionverma** [comment]
Great! Let me know if you need anything

**Comment by MauricioLudwig** [comment]
Hi, I realize someone was working on this already but I just made a pull request on this issue, seems every issue labeled hacktoberfest is taken. At worst use mine for inspiration although I think it looks really neat, lemme know what you think

**Comment by dillionverma** [comment]
Thank you @MauricioLudwig, I will check out your PR soon
