### ISSUE TITLE
Filter data by pull requests (react + redux)

### ISSUE THREAD

**Issue by dillionverma** [dillionverma/github-issues-explorer#16]
Right now, when fetching issues from github issues API, there are pull requests mixed in with the issues:
![image](https://user-images.githubusercontent.com/16860528/46882592-3c8c4800-ce1d-11e8-8e2e-e9ceb291d610.png)

We want to add another filter here: 
![image](https://user-images.githubusercontent.com/16860528/46882614-4ada6400-ce1d-11e8-99c2-622abd7e836a.png)

Such that we can filter by pull requests. 

To do this, you must have some knowledge or react/redux. Look into [here](https://github.com/dillionverma/github-issues-explorer/blob/master/src/features/Issues/reducer.js) to see how filtering works. You would need to add another conditional there to see if an issue is a pull request or not. [Here](https://github.com/dillionverma/github-issues-explorer/blob/master/src/features/Issues/Issues.js#L83) is where the filtering is activated from.

**Comment by Wgil** [comment]
Hello! I'll give this a try.

**Comment by dillionverma** [comment]
Great! Let me know if you need any help

**Comment by trblackw** [comment]
Going to look into this as well!
