### ISSUE TITLE
Responsive header css fix

### ISSUE THREAD

**Issue by dillionverma** [dillionverma/github-issues-explorer#18]
Prevent this from happening when on mobile devices

![image](https://user-images.githubusercontent.com/16860528/46883219-54fd6200-ce1f-11e8-9165-3d690ee00ced.png)

**Comment by sparkle-sparkle** [comment]
I would like to do this one

**Comment by dillionverma** [comment]
Great! Let me know if you need anything

**Comment by sparkle-sparkle** [comment]
<img width="607" alt="schermafbeelding 2018-10-12 om 19 58 26" src="https://user-images.githubusercontent.com/745519/46885777-46cc3780-ce59-11e8-85fd-c356f7a8a8ac.png">

I have found a solution. Is this what you want for small screens?

**Comment by dillionverma** [comment]
Looks great! Maybe you can even center the title for smaller screens. Might look even better @sparkle-sparkle

**Comment by sparkle-sparkle** [comment]
<img width="607" alt="schermafbeelding 2018-10-12 om 20 11 23" src="https://user-images.githubusercontent.com/745519/46886379-08377c80-ce5b-11e8-846a-bce8201449a8.png">
This is how it looks now

**Comment by dillionverma** [comment]
Perfect! Lets go with that, just make a PR and I will review the code too

**Comment by dillionverma** [comment]
Fixed be #22
