### ISSUE TITLE
Add page transition animations

### ISSUE THREAD

**Issue by dillionverma** [dillionverma/github-issues-explorer#2]
Add a simple transition effect between the landing page and the actual github issues page so it feels smoother.

This has to be done on the react router level. Most likely something in `App.js`.

See [this video](https://www.youtube.com/watch?v=lfcZFbdKjNE) for example

Can maybe look into [this post](https://hackernoon.com/animated-page-transitions-with-react-router-4-reacttransitiongroup-and-animated-1ca17bd97a1a) for inspiration

**Comment by MCLofton** [comment]
Neat idea, I'll try it.

**Comment by yasskate** [comment]
@dillionverma Can I work on this?

**Comment by dillionverma** [comment]
It's all yours! Let me know if you need anything.

**Comment by dillionverma** [comment]
Oh no :/ Don't worry about it @yasskate. Thanks for trying to help out!

**Comment by dekisr** [comment]
Hey @dillionverma , its me again. Maybe I should try it. I was able to apply the react-transition-group. It's working for issues to landing page. But from landing page to issues, the animation is going to the loading component. Any idea how to fix this?

**Comment by dillionverma** [comment]
The loading component appears if isLoading is true. Maybe something is occurring causing that value to be true. Did you already get an GitHub API access_token and set it up?

**Comment by dekisr** [comment]
Here how its working
![test](https://user-images.githubusercontent.com/38201274/47241354-b8f4cd00-d3c1-11e8-8e90-0af29b43e9bf.gif)
See the difference with and without loading

**Comment by dillionverma** [comment]
Wow looks amazing!! 
Yes, please open a pull request so we can merge it in.
Great stuff

**Comment by dekisr** [comment]
Alright, just sent the PR
