### ISSUE TITLE
Use CSS Grid instead of flex arbitrary values

### ISSUE THREAD

**Issue by thomlom** [dillionverma/github-issues-explorer#21]
I've noticed that the issues list is handled with flex and margin and the values seem to be chosen in an arbitrary way. 

While this is working perfectly, I think we can do better by making use of CSS Grid.

Basically, we just need to add this code into `.issues-container` :slightly_smiling_face: 

```css
display: grid;
grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));
grid-gap: 2rem;
```

**Comment by dillionverma** [comment]
Haha the css mistakes are me. I'm not the best with styling. Can you explain what `grid-template-columns` and `grid-gap` does? This is also the first time I'm seeing `minmax(400px, 1fr)`

**Comment by dillionverma** [comment]
Whoah, I literally have never seen those in use ever. Thanks so much for explaining. Maybe I might even take this issue to learn more about it.

**Comment by dillionverma** [comment]
I just tried that css trick and its so cool @thomlom. Definitely going in my notes.
