### ISSUE TITLE
Need back button in issue list page

### ISSUE THREAD

**Issue by sourav52** [dillionverma/github-issues-explorer#23]
In current scenario we don't have any back button to go landing page.

**Comment by dillionverma** [comment]
Great idea! This is up for grabs

**Comment by sourav52** [comment]
Hey @dillionverma instead of back button we can give search box.

**Comment by dillionverma** [comment]
That can be another issue! @sourav52. Feel free to create one

**Comment by trblackw** [comment]
So no back button then?

**Comment by dillionverma** [comment]
Back button is still up for grabs @trblackw.

Maybe you can place it here underneath the link, and in line with filters row
![image](https://user-images.githubusercontent.com/16860528/46888088-7d8c5880-ce2d-11e8-910c-9e5b209cebde.png)

**Comment by trblackw** [comment]
Awesome! I'll knock that out right quick
