### ISSUE TITLE
Needs .eslint 

### ISSUE THREAD

**Issue by gregorysl** [dillionverma/github-issues-explorer#26]
Currently my default eslint settings are clashing with project style, and I have to manually edit half of the file before commit

**Comment by dillionverma** [comment]
I haven't setup linting yet. This is a great issue and up for grabs

**Comment by dbrudner** [comment]
Are you trying to add eslint with airbnb's default settings or something else?

**Comment by dillionverma** [comment]
I think the airbnb is a good one to follow @dbrudner

**Comment by dbrudner** [comment]
https://github.com/dillionverma/github-issues-explorer/pull/32

**Comment by dillionverma** [comment]
resolved by #32
