### ISSUE TITLE
Change color of active filter

### ISSUE THREAD

**Issue by dillionverma** [dillionverma/github-issues-explorer#3]
Lets make the active filter have the primary color. Right now they are all the same.

![image](https://user-images.githubusercontent.com/16860528/46847568-19c54980-cdb3-11e8-8143-19ef33f181ab.png)

To do this, look into `src/Issues.css`

**Comment by Yathousen** [comment]
I'll take a look @dillionverma.

**Comment by Yathousen** [comment]
@dillionverma i just created a pull request, you can take a look at it [here](https://github.com/dillionverma/github-issues-explorer/pull/7). Hopefully it helps.

**Comment by dillionverma** [comment]
Great work, looks good to me. Just merged it in. Will close issue now.
