### ISSUE TITLE
Refactor css to scss

### ISSUE THREAD

**Issue by dillionverma** [dillionverma/github-issues-explorer#4]
Right now we are using a very unstructured way to style our issues viewer. Lets use scss which allows us to have nested styles.
 
![image](https://user-images.githubusercontent.com/16860528/46847764-023a9080-cdb4-11e8-83f9-1c4f511ff44a.png)

The two main files which need refactoring are [Landing.css](https://github.com/dillionverma/github-issues-explorer/blob/master/src/features/Issues/Landing.css) and [Issues.css](https://github.com/dillionverma/github-issues-explorer/blob/master/src/features/Issues/Issues.css).

The combined total lines of css is **150 lines**

Check [this tutorial](https://medium.com/@oreofeolurin/configuring-scss-with-react-create-react-app-1f563f862724) to get started.

**BONUS** Make scss variables for the colors which are repeated throughout the app

**Comment by vallendito** [comment]
hy @dillionverma it still available for pr?

**Comment by dillionverma** [comment]
Yes still available for PR. 

@max-ci awesome! I will check it out right now

**Comment by jkmdev** [comment]
Wait, what. I already said that I was working on this one...
Man that really sucks.

**Comment by dillionverma** [comment]
@jkmdev oh no don't worry! Nothing has been merged yet. I still have to look at your PR as welk

**Comment by dillionverma** [comment]
Sorry @jkmdev I just merged it in :( 
Feel free to try any other issues as well.
