### ISSUE TITLE
Github API Pagination

### ISSUE THREAD

**Issue by dillionverma** [dillionverma/github-issues-explorer#6]
# Implement pagination using the github API

Example:
https://api.github.com/repos/facebook/react/issues?state=all&page=2

To get started, add a `page` attribute to the state in the react component [here](https://github.com/dillionverma/github-issues-explorer/blob/master/src/features/Issues/Issues.js#L39)

Then, you have to pass the page number as a function argument to [this function](https://github.com/dillionverma/github-issues-explorer/blob/master/src/features/Issues/actions.js#L23) called from [here](https://github.com/dillionverma/github-issues-explorer/blob/master/src/features/Issues/Issues.js#L100) and [here](https://github.com/dillionverma/github-issues-explorer/blob/master/src/features/Issues/Issues.js#L51)

Last step would be adding a pagination component at the bottom of the page so that on click, the page number increases/decreases

Maybe look into [this component](https://github.com/vayser/react-js-pagination) to help out

**Comment by sajadhsm** [comment]
Can I take this?

**Comment by onlined** [comment]
I take this.

**Comment by onlined** [comment]
I leave this, sorry, it would take more time than I thought.

**Comment by dillionverma** [comment]
Oh no. That's alright, no worries.

This shouldn't be too long of a task, should take about 5 minutes once you understand the code. If you want, I can guide you. It's up to you.

**Comment by onlined** [comment]
The navigation component would take time, all the css and stuff...

**Comment by dillionverma** [comment]
The example [here](https://github.com/vayser/react-js-pagination) is very good. They show exactly how to set up the pagination component with a simple api. You would just be passing `activePage` to the api request in `actions.js`.

This is still up for grabs if anyone is interested #hacktoberfest

**Comment by thomlom** [comment]
Hey, I'd like to do this task. Is it OK for you @dillionverma ? :slightly_smiling_face:

**Comment by thomlom** [comment]
Pagination has been done @dillionverma! #20
